vsphere_user                 = ""
vsphere_password             = ""
data_center                  = ""
cluster                      = ""
datastore                    = ""
vsphere_host                 = ""
vsphere_network              = ""
compute_pool                 = ""
vsphere_server               = ""
vsphere_vapp_name            = ""
appliance_version            = ""
appliance_label_region       = ""
appliance_label_zone         = ""
appliance_master_cpu         = 
appliance_master_ram         = 
appliance_master_disk        = 
appliance_worker_cpu         = 
appliance_worker_ram         = 
appliance_worker_disk        = 
appliance_dns                = ""
appliance_gateway            = ""
appliance_master_ipaddresses = ["", "", ""]
appliance_master_hostnames   = ["", "", ""]
appliance_worker_ipaddresses = ["", "", ""]
appliance_worker_hostnames   = ["", "", ""]
appliance_ova                = ""